### ISSUE TITLE
Crash when non-NBT item is given for a trade requiring NBT

### ISSUE THREAD

**Issue by LavaSlayer** [malte0811/VillagerMetaFix#1]
Hi,

This is a great little mod which addresses an important issue.  Thank you for making this fix.

I have run into one problem, however.  When a villager requires a payment item which has NBT data, if I try to give him an item without NBT data, the game crashes.  (This is with B:checkNbtByDefault=true.)  However, the game does not crash if I give him an item with NBT, even if it is the wrong item or the wrong NBT.
This crash does not occur if I have B:checkNbtByDefault=false.
Also, the game does not crash if I give an NBT item when the villager requires a non-NBT item.

This is the crash message:

> Description: Unexpected error
> 
> java.lang.NullPointerException: Unexpected error
>   at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:145)
>   at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:390)
>   at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:357)
>   at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
>   at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
>   at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
>   at net.minecraft.client.main.Main.main(SourceFile:148)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Thank you.

**Comment by malte0811** [comment]
Thanks for reporting this. I know what the problem is,  I'll upload a new version in a few hours.
